### ISSUE TITLE
Revisi Modul 3

### ISSUE THREAD

**Issue by masnurrm** [arsitektur-jaringan-komputer/Modul-Jarkom#36]
@masnurrm 
- [x] dhcp relay masukin ke modul
- [x] lease-time (dhcp) untuk mencoba kinerja dhcp server 

Reference PR: #37

**Comment by masnurrm** [comment]
Can u guys review my PR Issue? @danielcristho @elshiraphine

**Comment by danielcristho** [comment]
Got it
